export const ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  PLUGIN_NOT_FOUND: "PLUGIN_NOT_FOUND",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  LLM_API_KEY_MISSING: "LLM_API_KEY_MISSING",
  LLM_UPSTREAM_ERROR: "LLM_UPSTREAM_ERROR",
  MCP_SERVER_NOT_FOUND: "MCP_SERVER_NOT_FOUND",
  MCP_PROBE_FAILED: "MCP_PROBE_FAILED",
  MCP_TOOL_NOT_FOUND: "MCP_TOOL_NOT_FOUND",
  MCP_INVOKE_FAILED: "MCP_INVOKE_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
